### ISSUE TITLE
签出项目数据迁移失败

### ISSUE THREAD

**Issue by wangbs-dev** [yanshengjie/UnitOfWork#1]
在【程序包管理器控制台】选择“UnitOfWork.Infrastructure”进行数据迁移失败。
步骤如下：
1.更改连接字符串
2.选中还原项目“UnitOfWork.Infrastructure”
3.Add-Migration Migrations

在第三步时，出错“Your startup project 'UnitOfWork.Application' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.”

安装了Microsoft.EntityFrameworkCore.Design      Entity Framework Core Tools

在“UnitOfWork.Infrastructure”也有一些历史迁移文件，想问一下你当初是怎么迁移的？
感谢！

**Comment by sheng-jie** [comment]
你要设置启动项目为UnitOfWork.Web

**Comment by wangbs-dev** [comment]
我刚刚重新clone到本地，设置启动项目为UnitOfWork.Web，编译，在Package Manager Console中选择UnitOfWork.Infrastructure，直接update-database成功了啊。不知道为什么你的不成功。你加我QQ吧：2098769873

**Comment by sheng-jie** [comment]
我刚刚重新clone到本地，设置启动项目为UnitOfWork.Web，编译，在Package Manager Console中选择UnitOfWork.Infrastructure，直接update-database成功了啊。不知道为什么你的不成功。你加我QQ吧：2098769873
