### ISSUE TITLE
请问是如何确保Uow和Reopository之间共享同一个DbContext实例？

### ISSUE THREAD

**Issue by ylwlf888** [yanshengjie/UnitOfWork#4]
public void CreateCustomer(Customer customer)
        {
            customer.ShoppingCart = new ShoppingCart.ShoppingCart();
            _customerRepository.Insert(customer);
            
            _unitOfWork.SaveChanges();
        }
以上两个仓库和_unitOfWork都是分别注入的，如何确保这两个仓库是使用的_unitOfWork的dbcontext?

**Comment by sheng-jie** [comment]
虽然是分别注入的，但注入的生命周期是Scoped，且属于一条调用链，所以，实际上他们将共用同一DbContext。可以详细了解下[.NET CORE依赖注入](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
